### ISSUE TITLE
Consider moving LICENSE.md to root folder

### ISSUE THREAD

**Issue by brylie** [tsloan1377/montreal_open_data#1]
The license file (LICENSE.md) is currently nested in a folder of the same name:

- /LICENSE.md/LICENSE.md

This is somewhat unconventional and redundant.

Consider moving the LICENSE.md file to the root level and removing the LICENSE.md/ folder:

- /LICENSE.md

**Comment by tsloan1377** [comment]
Thanks for letting me know, I've taken care of that. I appreciate the patience, I didn't notice the Issue until today.
